version: 2
jobs:
  build:
    docker:
      - image: reactcommunity/node-ci:8.4.0-0
    working_directory: ~/DailyScrum
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Paris"
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Copy dist environment
          command: cp environment/index.dist.js environment/index.js
      - run:
          name: Install deps
          command: yarn --frozen-lockfile
      - run:
          name: Tests
          command: yarn test
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
