# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyScrum' do
    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'BatchedBridge', # Required For React Native 0.45.0+
      'Core',
      'DevSupport',
      # Add any other subspecs you want to use in your project
    ]

    # Required by RNFirebase
    pod 'Firebase/Core'
    pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crash'
end
