# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyScrum' do
    # Required by RNFirebase
    pod 'Firebase/Core'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crash'
end
